# apiVersion: apps/v1
# kind: Deployment # Kubernetes resource kind we are creating
# metadata:
#   name: spring-boot-k8s-deployment
# spec:
#   selector:
#     matchLabels:
#       app: spring-boot-k8s
#   replicas: 2 # Number of replicas that will be created for this deployment
#   template:
#     metadata:
#       labels:
#         app: spring-boot-k8s
#     spec:
#       containers:
#         - name: spring-boot-k8s
#           image: suresh394/kubernetes # Image that will be used to containers in the cluster
#           imagePullPolicy: IfNotPresent
#           ports:
#             - containerPort: 8080 # The port that the container is running on in the cluster


# ---
# apiVersion: v1
# kind: Service 
# metadata: 
#   name: springboot-k8ssvc
# spec:
#   type: NodePort
#   selector:
#     app: spring-boot-k8s
#   ports:
#     - nodePort: 30163
#       port: 8080 
#       targetPort: 8080


apiVersion: apps/v1
kind: Deployment
metadata:
  name:  devops-automation
  namespace: production
spec:
  selector:
    matchLabels:
      app: devops-automation
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devops-automation
        tier: backend
    spec:
      containers:
      - name: devops-automation
        image: 533267326662.dkr.ecr.us-east-1.amazonaws.com/new-one-testing-rep
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1500Mi
        envFrom:
          - configMapRef:
              name: oamplus-configmap
        ports:
        - containerPort: 2009
      restartPolicy: Always
      imagePullSecrets:
      - name: aws-secret

---

apiVersion: v1
kind: Service
metadata:
  name: devops-automation
  namespace: production
spec:
  selector:
    app: devops-automation
  ports:
  - name: devops-automation
    protocol: TCP
    port: 2009
    targetPort: 2009

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-automation-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-automation
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120


